var rules = {
  'no-await-in-loop': 'error',
  'no-compare-neg-zero': 'warn',
  'no-constant-condition': 'warn',
  'no-dupe-args': 'warn',
  'no-dupe-keys': 'warn',
  'no-duplicate-case': 'warn',
  'no-empty': 'warn',
  'no-empty-character-class': 'warn',
  'no-ex-assign': 'warn',
  'no-extra-semi': 'warn',
  'no-func-assign': 'warn',
  'no-invalid-regexp': 'error',
  'no-obj-calls': 'error',
  'no-prototype-builtins': 'warn',
  'no-sparse-arrays': 'warn',
  'no-template-curly-in-string': 'error',
  'no-unexpected-multiline': 'warn',
  'no-unreachable': 'warn',
  'no-unsafe-finally': 'warn',
  'no-unsafe-negation': 'warn',
  'use-isnan': 'warn',
  'valid-typeof': 'warn',
  'no-console': 'warn',
  'no-cond-assign': 'error',
};

module.exports = rules;
