var rules = {
    'no-await-in-loop': 'error',
    'no-compare-neg-zero': 'error',
    'no-constant-condition': 'warn',
    'no-dupe-args': 'warn',
    'no-dupe-keys': 'warn',
    'no-duplicate-case': 'warn',
    'no-empty': 'warn',
    'no-empty-character-class': 'warn',
    'no-ex-assign': 'error',
    'no-extra-semi': 'warn',
    'no-func-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-obj-calls': 'error',
    'no-prototype-builtins': 'error',
    'no-sparse-arrays': 'warn',
    'no-template-curly-in-string': 'error',
    'no-unexpected-multiline': 'error',
    'no-unreachable': 'warn',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'warn',
    'use-isnan': 'error',
    'valid-typeof': 'warn',
};

module.exports = rules;
